Implement task board
antlu/task-manager pull request #15
Opened 2021-12-20 09:09 UTC by antlu

2021-12-20 16:48 UTC, greybutton requested changes

2021-12-20 16:48 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    tasks = Task.all.order('created_at desc').ransack(ransack_params).result.page(page).per(per_page)
ордер не задается через орм, нужно задавать через рансак

2021-12-20 16:48 UTC, greybutton commented on app/javascript/components/AddPopup/AddPopup.js
> +import TaskForm from '../../forms/TaskForm.js';
from 'forms/TaskForm';

2021-12-20 16:48 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +
из относительный путей будет только import useStyles from './useStyles';

2021-12-20 16:48 UTC, greybutton commented on package.json
> +    "ramda": "^0.27.1",
qs не хватает

2021-12-21 15:43 UTC, greybutton requested changes

2021-12-21 15:43 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    search.sorts = 'created_at desc'
это тоже не то, не задается сортировка в контроллере. Ее ставит фронт обычно, либо дефолт какой то есть

2021-12-21 18:23 UTC, antlu commented on app/controllers/api/v1/application_controller.rb
> +    { s: RANSACK_DEFAULT_SORT }.merge(params.to_unsafe_h.fetch(:q, {}))
Если и так не пойдёт, могу ещё 
```js
TasksRepository.index({
      q: { stateEq: state, s: 'created_at desc' }
      ...
```

2021-12-22 06:47 UTC, greybutton approved these changes

2021-12-22 07:00 UTC, merged