Add Redux
antlu/task-manager pull request #17
Opened 2021-12-29 15:12 UTC by antlu

2021-12-29 19:15 UTC, greybutton requested changes

2021-12-29 19:15 UTC, greybutton commented on app/javascript/slices/tasksSlice.js
> +});
нужно все действия делать через редакс, не только загрузку колонки

2021-12-29 20:00 UTC, antlu commented on app/javascript/slices/tasksSlice.js
> +});
А я посчитал, что использование loadColumn в других обработчиках – это тоже путь "через Redux".

2022-01-12 18:54 UTC, greybutton commented on app/javascript/slices/tasksSlice.js
> +});
почему useTasksActions в отдельный файл вынес?

2022-01-12 19:27 UTC, antlu commented on app/javascript/slices/tasksSlice.js
> +});
Название как у хука, а для них отдельная директория есть. Решил не устраивать мешанину в слайсе.

2022-01-12 20:03 UTC, greybutton approved these changes

2022-01-13 05:06 UTC, merged