Add FSM
antlu/task-manager pull request #6
Opened 2021-11-21 12:29 UTC by antlu

2021-11-21 19:26 UTC, greybutton requested changes

2021-11-21 19:26 UTC, greybutton commented on app/models/task.rb
> +class Task < ActiveRecord::Base
почему поменял?

2021-11-21 19:26 UTC, greybutton commented on app/models/task.rb
> +    event :to_qa do
название ивента - глагол

2021-11-21 21:29 UTC, antlu commented on app/models/task.rb
> +class Task < ActiveRecord::Base
По примеру из описания библиотеки. 
Теперь в документации увидел 

> `ApplicationRecord` inherits from `ActiveRecord::Base`

2021-11-22 15:43 UTC, greybutton approved these changes

2021-11-22 16:28 UTC, merged